version: "3.8"
services:
  app:
    build:
      context: ./docker/php
    container_name: campanias_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    networks:
      - campanias

  nginx:
    image: nginx:latest
    container_name: campanias_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - campanias

  postgres:
    image: postgres:16.8
    container_name: campanias_postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: campanias_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: campanias
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - campanias

  adminer:
    image: adminer:latest
    container_name: campanias_adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - campanias

  node:
    image: node:22-alpine
    container_name: campanias_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - campanias
  composer:
    build:
      context: ./docker/php
    container_name: campanias_composer
    working_dir: /var/www
    volumes:
      - .:/var/www
    entrypoint: ["composer"]
    networks:
      - campanias

networks:
  campanias:
    driver: bridge

volumes:
  postgres_data: